PROC ON_FILL;
  PRG_START(COMMAND.ON_M54_M55);
  PRG_START(COMMAND.ON_M61);
  PRG_START(COMMAND.ON_M52);
  PRG_START(COMMAND.WAIT_CONVEYOR_FILL);
ENDPROC

PROC OFF_FILL;
  PRG_START(COMMAND.OFF_M54_M55);
  PRG_START(COMMAND.OFF_M61);
  PRG_START(COMMAND.OFF_M52);
  PRG_START(COMMAND.OFF_CONVEYOR_FILL);
ENDPROC

PROC ON_M54_M55;
  OFF(M55);
  ON(M54);
  WAIT(,TIMER_M54_M55,TIME_M54_M55);
  OFF(M54);
  ON(M55);
  WAIT(,TIMER_M54_M55,TIME_M54_M55);
  LOOP;  
ENDPROC

PROC ON_M54&M55;
    ON(M54);
    ON(M54);
ENDPROC

PROC OFF_M54_M55;
  PRG_STOP(COMMAND.ON_M54_M55);
  OFF(M54);
  OFF(M55);
ENDPROC

;-------------- Conveyor fill -----------------------------------------

PROC WAIT_CONVEYOR_FILL;
  PRG_START(COMMAND.ON_CONVEYOR_FILL);
  WAIT(SL13);
  PRG_START(COMMAND.OFF_CONVEYOR_FILL);
ENDPROC

PROC ON_CONVEYOR_FILL;
  ON(M22);
  ON(M24);
  ON(M25);
ENDPROC

PROC OFF_CONVEYOR_FILL;
  PRG_STOP(COMMAND.WAIT_CONVEYOR_FILL);
  OFF(M22);
  OFF(M24);
  OFF(M25);
ENDPROC

;-----------------------------------------------------

PROC ON_FILL_LOV;
   OFF(M51);
   ON(YA52);
   WAIT(SL509 || SL508 || SL507 || SL506,,);
   PRG_START(COMMAND.ON_M54_M55);
   WAIT(SL507 || SL506, TIMER_WAIT_SL507, TIME_WAIT_SL507);
   IF(SL507 || SL506)
     OFF(YA52);
   END;
   IF(! SL507 && ! SL506)
     MSG(0000, Error: Wait 30m and not SL507);
     OFF(YA52);
   END;
ENDPROC

PROC OFF_FILL_LOV;
  PRG_STOP(COMMAND.ON_FILL_LOV);
  OFF(YA52);
ENDPROC

;==============
PROC ON_M11;
  ON(M11);
ENDPROC

PROC OFF_M11;
  OFF(M11);
ENDPROC

PROC ON_M12;
  ON(M12);
ENDPROC

PROC OFF_M12;
  OFF(M12);
ENDPROC

PROC ON_M22;
  ON(M22);
ENDPROC

PROC OFF_M22;
  OFF(M22);
ENDPROC

PROC ON_M24;
  ON(M24);
ENDPROC

PROC OFF_M24;
  OFF(M24);
ENDPROC

PROC ON_M25;
  ON(M25);
ENDPROC

PROC OFF_M25;
  OFF(M25);
ENDPROC

PROC ON_M51;
  ON(M51);
ENDPROC

PROC OFF_M51;
  OFF(M51);
ENDPROC

PROC ON_M52;
  ON(M52);
ENDPROC

PROC OFF_M52;
  OFF(M52);
ENDPROC

PROC ON_M61;
  ON(M61);
ENDPROC

PROC OFF_M61;
  OFF(M61);
ENDPROC

PROC ON_M23_2;
  ON(M23.2);
ENDPROC

PROC OFF_M23_2;
  OFF(M23.2);
ENDPROC

PROC ON_YK53;
  ON(YA53);
ENDPROC

PROC OFF_YK53;
  OFF(YA53);
ENDPROC
